# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.grpc.proto.server import user_pb2 as src_dot_grpc_dot_proto_dot_server_dot_user__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in src/grpc/proto/server/user_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserPreferenceServiceStub(object):
    """Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPreference = channel.unary_unary(
                '/user.UserPreferenceService/GetPreference',
                request_serializer=src_dot_grpc_dot_proto_dot_server_dot_user__pb2.GetPreferenceRequest.SerializeToString,
                response_deserializer=src_dot_grpc_dot_proto_dot_server_dot_user__pb2.PreferenceResponse.FromString,
                _registered_method=True)
        self.UpdatePreference = channel.unary_unary(
                '/user.UserPreferenceService/UpdatePreference',
                request_serializer=src_dot_grpc_dot_proto_dot_server_dot_user__pb2.UpdatePreferenceRequest.SerializeToString,
                response_deserializer=src_dot_grpc_dot_proto_dot_server_dot_user__pb2.PreferenceResponse.FromString,
                _registered_method=True)
        self.GetNotificationSetting = channel.unary_unary(
                '/user.UserPreferenceService/GetNotificationSetting',
                request_serializer=src_dot_grpc_dot_proto_dot_server_dot_user__pb2.GetPreferenceRequest.SerializeToString,
                response_deserializer=src_dot_grpc_dot_proto_dot_server_dot_user__pb2.NotificationResponse.FromString,
                _registered_method=True)
        self.UpdateNotificationSetting = channel.unary_unary(
                '/user.UserPreferenceService/UpdateNotificationSetting',
                request_serializer=src_dot_grpc_dot_proto_dot_server_dot_user__pb2.UpdateNotificationRequest.SerializeToString,
                response_deserializer=src_dot_grpc_dot_proto_dot_server_dot_user__pb2.NotificationResponse.FromString,
                _registered_method=True)
        self.GetPrivacySetting = channel.unary_unary(
                '/user.UserPreferenceService/GetPrivacySetting',
                request_serializer=src_dot_grpc_dot_proto_dot_server_dot_user__pb2.GetPreferenceRequest.SerializeToString,
                response_deserializer=src_dot_grpc_dot_proto_dot_server_dot_user__pb2.PrivacyResponse.FromString,
                _registered_method=True)
        self.UpdatePrivacySetting = channel.unary_unary(
                '/user.UserPreferenceService/UpdatePrivacySetting',
                request_serializer=src_dot_grpc_dot_proto_dot_server_dot_user__pb2.UpdatePrivacyRequest.SerializeToString,
                response_deserializer=src_dot_grpc_dot_proto_dot_server_dot_user__pb2.PrivacyResponse.FromString,
                _registered_method=True)
        self.CreateConsent = channel.unary_unary(
                '/user.UserPreferenceService/CreateConsent',
                request_serializer=src_dot_grpc_dot_proto_dot_server_dot_user__pb2.CreateConsentRequest.SerializeToString,
                response_deserializer=src_dot_grpc_dot_proto_dot_server_dot_user__pb2.CreateConsentResponse.FromString,
                _registered_method=True)
        self.GetConsentHistory = channel.unary_unary(
                '/user.UserPreferenceService/GetConsentHistory',
                request_serializer=src_dot_grpc_dot_proto_dot_server_dot_user__pb2.GetConsentHistoryRequest.SerializeToString,
                response_deserializer=src_dot_grpc_dot_proto_dot_server_dot_user__pb2.GetConsentHistoryResponse.FromString,
                _registered_method=True)
        self.GetLatestConsent = channel.unary_unary(
                '/user.UserPreferenceService/GetLatestConsent',
                request_serializer=src_dot_grpc_dot_proto_dot_server_dot_user__pb2.GetLatestConsentRequest.SerializeToString,
                response_deserializer=src_dot_grpc_dot_proto_dot_server_dot_user__pb2.GetLatestConsentResponse.FromString,
                _registered_method=True)


class UserPreferenceServiceServicer(object):
    """Service
    """

    def GetPreference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePreference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNotificationSetting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateNotificationSetting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPrivacySetting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePrivacySetting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateConsent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConsentHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLatestConsent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserPreferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPreference': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPreference,
                    request_deserializer=src_dot_grpc_dot_proto_dot_server_dot_user__pb2.GetPreferenceRequest.FromString,
                    response_serializer=src_dot_grpc_dot_proto_dot_server_dot_user__pb2.PreferenceResponse.SerializeToString,
            ),
            'UpdatePreference': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePreference,
                    request_deserializer=src_dot_grpc_dot_proto_dot_server_dot_user__pb2.UpdatePreferenceRequest.FromString,
                    response_serializer=src_dot_grpc_dot_proto_dot_server_dot_user__pb2.PreferenceResponse.SerializeToString,
            ),
            'GetNotificationSetting': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNotificationSetting,
                    request_deserializer=src_dot_grpc_dot_proto_dot_server_dot_user__pb2.GetPreferenceRequest.FromString,
                    response_serializer=src_dot_grpc_dot_proto_dot_server_dot_user__pb2.NotificationResponse.SerializeToString,
            ),
            'UpdateNotificationSetting': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateNotificationSetting,
                    request_deserializer=src_dot_grpc_dot_proto_dot_server_dot_user__pb2.UpdateNotificationRequest.FromString,
                    response_serializer=src_dot_grpc_dot_proto_dot_server_dot_user__pb2.NotificationResponse.SerializeToString,
            ),
            'GetPrivacySetting': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrivacySetting,
                    request_deserializer=src_dot_grpc_dot_proto_dot_server_dot_user__pb2.GetPreferenceRequest.FromString,
                    response_serializer=src_dot_grpc_dot_proto_dot_server_dot_user__pb2.PrivacyResponse.SerializeToString,
            ),
            'UpdatePrivacySetting': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePrivacySetting,
                    request_deserializer=src_dot_grpc_dot_proto_dot_server_dot_user__pb2.UpdatePrivacyRequest.FromString,
                    response_serializer=src_dot_grpc_dot_proto_dot_server_dot_user__pb2.PrivacyResponse.SerializeToString,
            ),
            'CreateConsent': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateConsent,
                    request_deserializer=src_dot_grpc_dot_proto_dot_server_dot_user__pb2.CreateConsentRequest.FromString,
                    response_serializer=src_dot_grpc_dot_proto_dot_server_dot_user__pb2.CreateConsentResponse.SerializeToString,
            ),
            'GetConsentHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConsentHistory,
                    request_deserializer=src_dot_grpc_dot_proto_dot_server_dot_user__pb2.GetConsentHistoryRequest.FromString,
                    response_serializer=src_dot_grpc_dot_proto_dot_server_dot_user__pb2.GetConsentHistoryResponse.SerializeToString,
            ),
            'GetLatestConsent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestConsent,
                    request_deserializer=src_dot_grpc_dot_proto_dot_server_dot_user__pb2.GetLatestConsentRequest.FromString,
                    response_serializer=src_dot_grpc_dot_proto_dot_server_dot_user__pb2.GetLatestConsentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'user.UserPreferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('user.UserPreferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserPreferenceService(object):
    """Service
    """

    @staticmethod
    def GetPreference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.UserPreferenceService/GetPreference',
            src_dot_grpc_dot_proto_dot_server_dot_user__pb2.GetPreferenceRequest.SerializeToString,
            src_dot_grpc_dot_proto_dot_server_dot_user__pb2.PreferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePreference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.UserPreferenceService/UpdatePreference',
            src_dot_grpc_dot_proto_dot_server_dot_user__pb2.UpdatePreferenceRequest.SerializeToString,
            src_dot_grpc_dot_proto_dot_server_dot_user__pb2.PreferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNotificationSetting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.UserPreferenceService/GetNotificationSetting',
            src_dot_grpc_dot_proto_dot_server_dot_user__pb2.GetPreferenceRequest.SerializeToString,
            src_dot_grpc_dot_proto_dot_server_dot_user__pb2.NotificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateNotificationSetting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.UserPreferenceService/UpdateNotificationSetting',
            src_dot_grpc_dot_proto_dot_server_dot_user__pb2.UpdateNotificationRequest.SerializeToString,
            src_dot_grpc_dot_proto_dot_server_dot_user__pb2.NotificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPrivacySetting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.UserPreferenceService/GetPrivacySetting',
            src_dot_grpc_dot_proto_dot_server_dot_user__pb2.GetPreferenceRequest.SerializeToString,
            src_dot_grpc_dot_proto_dot_server_dot_user__pb2.PrivacyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePrivacySetting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.UserPreferenceService/UpdatePrivacySetting',
            src_dot_grpc_dot_proto_dot_server_dot_user__pb2.UpdatePrivacyRequest.SerializeToString,
            src_dot_grpc_dot_proto_dot_server_dot_user__pb2.PrivacyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateConsent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.UserPreferenceService/CreateConsent',
            src_dot_grpc_dot_proto_dot_server_dot_user__pb2.CreateConsentRequest.SerializeToString,
            src_dot_grpc_dot_proto_dot_server_dot_user__pb2.CreateConsentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConsentHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.UserPreferenceService/GetConsentHistory',
            src_dot_grpc_dot_proto_dot_server_dot_user__pb2.GetConsentHistoryRequest.SerializeToString,
            src_dot_grpc_dot_proto_dot_server_dot_user__pb2.GetConsentHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLatestConsent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.UserPreferenceService/GetLatestConsent',
            src_dot_grpc_dot_proto_dot_server_dot_user__pb2.GetLatestConsentRequest.SerializeToString,
            src_dot_grpc_dot_proto_dot_server_dot_user__pb2.GetLatestConsentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
